import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Use service role key for API routes (bypass RLS)
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.PRIVATE_SUPABASE_SERVICE_KEY!;

/**
 * POST /api/flights
 * Endpoint for Power Automate to send drone flight events
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate required fields
    if (!body.timestamp || !body.drone) {
      return NextResponse.json(
        { error: 'Missing required fields: timestamp and drone are required' },
        { status: 400 }
      );
    }

    // Create Supabase client with service role key
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse coordinates if present
    let latitude = null;
    let longitude = null;
    if (body.coordinates) {
      const coords = body.coordinates.split(',').map((c: string) => parseFloat(c.trim()));
      if (coords.length === 2) {
        latitude = coords[0];
        longitude = coords[1];
      }
    }

    // Prepare flight data (explicitly exclude 'id' to prevent conflicts with auto-generated PK)
    const flightData = {
      event_id: body.eventId || body.event_id,
      message: body.message,
      severity: body.severity || 'INFO',
      drone: body.drone,
      dock: body.dock,
      coordinates: body.coordinates,
      latitude,
      longitude,
      altitude: body.altitude,
      site: body.site,
      organization: body.organization,
      automation: body.automation,
      battery: body.battery,
      flight_details: body.flightDetails || body.flight_details,
      timestamp_gmt: new Date(body.timestamp).toISOString(),
      // Note: 'id' is intentionally excluded - it's auto-generated by the database
    };

    // Insert into database
    const { data, error } = await supabase
      .from('drone_flights')
      .insert([flightData])
      .select();

    if (error) {
      console.error('Error inserting flight data:', error);
      return NextResponse.json(
        { error: 'Failed to insert flight data', details: error.message },
        { status: 500 }
      );
    }

    console.log('✅ Flight data inserted:', data[0].id);

    return NextResponse.json(
      {
        success: true,
        message: 'Flight data received and stored',
        id: data[0].id,
      },
      { status: 201 }
    );

  } catch (error: any) {
    console.error('Error processing flight data:', error);
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    );
  }
}

/**
 * GET /api/flights
 * Optional: Retrieve flights (for testing)
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { searchParams } = new URL(request.url);
    const limit = parseInt(searchParams.get('limit') || '10');

    const { data, error } = await supabase
      .from('drone_flights')
      .select('*')
      .order('timestamp_gmt', { ascending: false })
      .limit(limit);

    if (error) {
      return NextResponse.json(
        { error: 'Failed to fetch flights', details: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      count: data.length,
      flights: data,
    });

  } catch (error: any) {
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    );
  }
}
