-- Create drone_flights table for storing drone flight events
create table "public"."drone_flights" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" text,
    "message" text,
    "severity" text,
    "drone" text,
    "dock" text,
    "coordinates" text,
    "latitude" numeric,
    "longitude" numeric,
    "altitude" text,
    "site" text,
    "organization" text,
    "automation" text,
    "battery" text,
    "flight_details" text,
    "timestamp_gmt" timestamp with time zone not null
);

-- Enable Row Level Security
alter table "public"."drone_flights" enable row level security;

-- Create primary key
CREATE UNIQUE INDEX drone_flights_pkey ON public.drone_flights USING btree (id);
alter table "public"."drone_flights" add constraint "drone_flights_pkey" PRIMARY KEY using index "drone_flights_pkey";

-- Create indexes for common queries
CREATE INDEX idx_drone_flights_timestamp ON public.drone_flights USING btree (timestamp_gmt DESC);
CREATE INDEX idx_drone_flights_drone ON public.drone_flights USING btree (drone);
CREATE INDEX idx_drone_flights_site ON public.drone_flights USING btree (site);
CREATE INDEX idx_drone_flights_organization ON public.drone_flights USING btree (organization);
CREATE INDEX idx_drone_flights_automation ON public.drone_flights USING btree (automation);

-- Grant permissions to anon role (for public read access if needed)
grant select on table "public"."drone_flights" to "anon";

-- Grant full permissions to authenticated users
grant delete on table "public"."drone_flights" to "authenticated";
grant insert on table "public"."drone_flights" to "authenticated";
grant references on table "public"."drone_flights" to "authenticated";
grant select on table "public"."drone_flights" to "authenticated";
grant trigger on table "public"."drone_flights" to "authenticated";
grant truncate on table "public"."drone_flights" to "authenticated";
grant update on table "public"."drone_flights" to "authenticated";

-- Grant full permissions to service_role
grant delete on table "public"."drone_flights" to "service_role";
grant insert on table "public"."drone_flights" to "service_role";
grant references on table "public"."drone_flights" to "service_role";
grant select on table "public"."drone_flights" to "service_role";
grant trigger on table "public"."drone_flights" to "service_role";
grant truncate on table "public"."drone_flights" to "service_role";
grant update on table "public"."drone_flights" to "service_role";

-- Create RLS policies
-- Allow authenticated users to read all flight data
create policy "Authenticated users can read all flights"
on "public"."drone_flights"
as permissive
for select
to authenticated
using (true);

-- Allow authenticated users to insert flight data
create policy "Authenticated users can insert flights"
on "public"."drone_flights"
as permissive
for insert
to authenticated
with check (true);

-- Allow service role full access
create policy "Service role has full access"
on "public"."drone_flights"
as permissive
for all
to service_role
using (true);
